api_platform:
  title: 'darts-scoreboard'
  description: 'Providing communication between darts game clients and gae storage. '
  version: '0.0.1'
  name_converter: ~
  enable_swagger: true
  enable_swagger_ui: true
  enable_entrypoint: true
  enable_docs: true

  swagger:
    api_keys: []

  collection:
    order: 'ASC'
    order_parameter_name: 'order'
    pagination:
      enabled: true
      client_enabled: false
      client_items_per_page: false
      items_per_page: 10
      maximum_items_per_page: 100
      page_parameter_name: 'page'
      enabled_parameter_name: 'pagination'
      items_per_page_parameter_name: 'itemsPerPage'
      partial: true
      client_partial: true
      partial_parameter_name: 'partial' # Default value

  mapping:
    paths: []

  resource_class_directories:
  - '%kernel.project_dir%/src/Entity'

  http_cache:
    etag: true
    vary: ['Accept']
    invalidation:
      enabled: false

  exception_to_status:
    Symfony\Component\Serializer\Exception\ExceptionInterface: 400

  formats:
    json:
      mime_types: ['application/json']
    html:
      mime_types: ['text/html']